/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#include "alignment_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression

TEST(regression, passthrough_test_1)
{
    __attribute__ ((aligned(32768))) char x[] = "accbccccaa";
    char actual = *passthrough(x);
    EXPECT_EQ('a', actual);
    char expected_x[] = {'a', 'c', 'c', 'b', 'c', 'c', 'c', 'c', 'a', '\0'};
    for (int it_1_0 = 0; it_1_0 < 10; it_1_0 ++) {
        EXPECT_EQ(expected_x[it_1_0], x[it_1_0]);
    }
}

#pragma endregion
}
