/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "bits_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, NSE_BITS_CLZ64_test_1)
{
    unsigned int actual = NSE_BITS_CLZ64(0ULL);
    EXPECT_EQ(64U, actual);
}

TEST(regression, NSE_BITS_CLZ64_test_2)
{
    unsigned int actual = NSE_BITS_CLZ64(9259542123273814144ULL);
    EXPECT_EQ(0U, actual);
}

TEST(regression, foo1_test_1)
{
    struct tagFOO_ATTRIBUTE attrib[10] = {{
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 4U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}};
    unsigned int offset = 0U;
    unsigned int len = 0U;
    unsigned int actual = foo1(attrib, 3U, 0U, &offset, &len);
    EXPECT_EQ(0U, actual);
    unsigned int expected_offset = 0U;
    EXPECT_EQ(expected_offset, offset);
    unsigned int expected_len = 0U;
    EXPECT_EQ(expected_len, len);
}

TEST(regression, foo1_test_2)
{
    struct tagFOO_ATTRIBUTE attrib[10] = {{
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 1U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}};
    unsigned int offset = 0U;
    unsigned int len = 0U;
    unsigned int actual = foo1(attrib, 4U, 1U, &offset, &len);
    EXPECT_EQ(0U, actual);
    unsigned int expected_offset = 0U;
    EXPECT_EQ(expected_offset, offset);
    unsigned int expected_len = 0U;
    EXPECT_EQ(expected_len, len);
}

TEST(regression, foo1_test_3)
{
    struct tagFOO_ATTRIBUTE attrib[10] = {{
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}};
    unsigned int offset = 0U;
    unsigned int len = 0U;
    unsigned int actual = foo1(attrib, 2U, 0U, &offset, &len);
    EXPECT_EQ(0U, actual);
    unsigned int expected_offset = 0U;
    EXPECT_EQ(expected_offset, offset);
    unsigned int expected_len = 0U;
    EXPECT_EQ(expected_len, len);
}

TEST(regression, foo1_test_4)
{
    struct tagFOO_ATTRIBUTE attrib[10] = {{
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}, {
        .offset = 0U,
        .len = 0U,
        .id = 0U}};
    unsigned int offset = 0U;
    unsigned int len = 0U;
    unsigned int actual = foo1(attrib, 0U, 0U, &offset, &len);
    EXPECT_EQ(1U, actual);
    unsigned int expected_offset = 0U;
    EXPECT_EQ(expected_offset, offset);
    unsigned int expected_len = 0U;
    EXPECT_EQ(expected_len, len);
}

#pragma endregion
#pragma region error
TEST(error, foo1_test_5)
{
    struct tagFOO_ATTRIBUTE attrib[10] = {{
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}, {
        .offset = 0U,
        .len = 0U,
        .id = 8U}};
    unsigned int offset = 0U;
    unsigned int len = 0U;
    foo1(attrib, 255U, 0U, &offset, &len);
}

#pragma endregion
}
