/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "static_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;
// Function 'inline_sum' was skipped, as inline function without static or extern modifier is not supported by now



#pragma region regression
TEST(regression, static_simple_test_1)
{
    x = 1;
    int actual = static_simple(-1);
    EXPECT_EQ(0, actual);
    int expected_x = 1;
    EXPECT_EQ(expected_x, x);
}

TEST(regression, static_simple_test_2)
{
    x = -10;
    int actual = static_simple(-10);
    EXPECT_EQ(0, actual);
    int expected_x = -10;
    EXPECT_EQ(expected_x, x);
}

TEST(regression, static_simple_test_3)
{
    x = 0;
    int actual = static_simple(0);
    EXPECT_EQ(0, actual);
    int expected_x = 0;
    EXPECT_EQ(expected_x, x);
}

TEST(regression, static_accept_local_struct_test_1)
{
    int actual = static_accept_local_struct({
        .x = 0,
        .y = 0}, 0);
    EXPECT_EQ(0, actual);
}

TEST(regression, static_accept_local_struct_test_2)
{
    int actual = static_accept_local_struct({
        .x = 0,
        .y = 0}, 1);
    EXPECT_EQ(0, actual);
}

TEST(regression, static_accept_local_struct_test_3)
{
    int actual = static_accept_local_struct({
        .x = 0,
        .y = 0}, 2);
    EXPECT_EQ(0, actual);
}

TEST(regression, static_return_local_struct_test_1)
{
    struct StaticStruct actual = static_return_local_struct(0, 0);
    struct StaticStruct expected = {
        .x = 0,
        .y = 0};
}

TEST(regression, static_inline_sum_test_1)
{
    int actual = static_inline_sum(0, 0);
    EXPECT_EQ(0, actual);
}

#pragma endregion
}
