//1656430452000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define _Alignas(x)
enum __Sign {
    NEG1,
    ZER1,
    POS1
};

typedef enum __Sign Sign1;

typedef enum  {
    NEG2,
    ZER2,
    POS2
} Sign2;


