// 1656451883000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "typedefs_1_stub.h"

#define NULL ((void*)0)

int gid_to_name_symbolic[10];
int _gid_to_name_symbolic[10];
int gid_to_name(gid_t gid) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_gid_to_name_symbolic, sizeof(_gid_to_name_symbolic), "_gid_to_name_symbolic");
            for (int it_41_0 = 0; it_41_0 < 10; it_41_0 ++) {
                klee_prefer_cex(_gid_to_name_symbolic, _gid_to_name_symbolic[it_41_0] >= -10  & _gid_to_name_symbolic[it_41_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _gid_to_name_symbolic[cntCall++];
}


int sign_of_typedef_struct_symbolic[10];
int _sign_of_typedef_struct_symbolic[10];
int sign_of_typedef_struct(TypeDefStruct x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_sign_of_typedef_struct_symbolic, sizeof(_sign_of_typedef_struct_symbolic), "_sign_of_typedef_struct_symbolic");
            for (int it_42_0 = 0; it_42_0 < 10; it_42_0 ++) {
                klee_prefer_cex(_sign_of_typedef_struct_symbolic, _sign_of_typedef_struct_symbolic[it_42_0] >= -10  & _sign_of_typedef_struct_symbolic[it_42_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _sign_of_typedef_struct_symbolic[cntCall++];
}


int sign_of_typedef_struct2_symbolic[10];
int _sign_of_typedef_struct2_symbolic[10];
int sign_of_typedef_struct2(TypeDefStruct2 x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_sign_of_typedef_struct2_symbolic, sizeof(_sign_of_typedef_struct2_symbolic), "_sign_of_typedef_struct2_symbolic");
            for (int it_43_0 = 0; it_43_0 < 10; it_43_0 ++) {
                klee_prefer_cex(_sign_of_typedef_struct2_symbolic, _sign_of_typedef_struct2_symbolic[it_43_0] >= -10  & _sign_of_typedef_struct2_symbolic[it_43_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _sign_of_typedef_struct2_symbolic[cntCall++];
}


int sign_of_typedef_union_symbolic[10];
int _sign_of_typedef_union_symbolic[10];
int sign_of_typedef_union(TypeDefUnion x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_sign_of_typedef_union_symbolic, sizeof(_sign_of_typedef_union_symbolic), "_sign_of_typedef_union_symbolic");
            for (int it_44_0 = 0; it_44_0 < 10; it_44_0 ++) {
                klee_prefer_cex(_sign_of_typedef_union_symbolic, _sign_of_typedef_union_symbolic[it_44_0] >= -10  & _sign_of_typedef_union_symbolic[it_44_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _sign_of_typedef_union_symbolic[cntCall++];
}


int sign_of_typedef_union2_symbolic[10];
int _sign_of_typedef_union2_symbolic[10];
int sign_of_typedef_union2(TypeDefUnion2 x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_sign_of_typedef_union2_symbolic, sizeof(_sign_of_typedef_union2_symbolic), "_sign_of_typedef_union2_symbolic");
            for (int it_45_0 = 0; it_45_0 < 10; it_45_0 ++) {
                klee_prefer_cex(_sign_of_typedef_union2_symbolic, _sign_of_typedef_union2_symbolic[it_45_0] >= -10  & _sign_of_typedef_union2_symbolic[it_45_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _sign_of_typedef_union2_symbolic[cntCall++];
}


unsigned long min_size_t_symbolic[10];
unsigned long _min_size_t_symbolic[10];
unsigned long min_size_t(size_t a, size_t b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_min_size_t_symbolic, sizeof(_min_size_t_symbolic), "_min_size_t_symbolic");
            for (int it_46_0 = 0; it_46_0 < 10; it_46_0 ++) {
                klee_prefer_cex(_min_size_t_symbolic, _min_size_t_symbolic[it_46_0]<= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _min_size_t_symbolic[cntCall++];
}


unsigned long min_size_t_alias_symbolic[10];
unsigned long _min_size_t_alias_symbolic[10];
unsigned long min_size_t_alias(size_t_alias a, size_t_alias b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_min_size_t_alias_symbolic, sizeof(_min_size_t_alias_symbolic), "_min_size_t_alias_symbolic");
            for (int it_47_0 = 0; it_47_0 < 10; it_47_0 ++) {
                klee_prefer_cex(_min_size_t_alias_symbolic, _min_size_t_alias_symbolic[it_47_0]<= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _min_size_t_alias_symbolic[cntCall++];
}


