// 1655848521000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "types_2_stub.h"

#define NULL ((void*)0)

unsigned long foo_symbolic[10];
unsigned long foo_symbolic[10];
unsigned long foo(int x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&foo_symbolic, sizeof(foo_symbolic), "foo_symbolic");
            for (int it_12_0 = 0; it_12_0 < 10; it_12_0 ++) {
                klee_prefer_cex(foo_symbolic, foo_symbolic[it_12_0]<= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return foo_symbolic[cntCall++];
}


int bar_symbolic[10];
int bar_symbolic[10];
int bar(size_t a, int b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&bar_symbolic, sizeof(bar_symbolic), "bar_symbolic");
            for (int it_12_0 = 0; it_12_0 < 10; it_12_0 ++) {
                klee_prefer_cex(bar_symbolic, bar_symbolic[it_12_0] >= -10  & bar_symbolic[it_12_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return bar_symbolic[cntCall++];
}


unsigned int diff_symbolic[10];
unsigned int diff_symbolic[10];
unsigned int diff(int x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&diff_symbolic, sizeof(diff_symbolic), "diff_symbolic");
            for (int it_13_0 = 0; it_13_0 < 10; it_13_0 ++) {
                klee_prefer_cex(diff_symbolic, diff_symbolic[it_13_0]<= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return diff_symbolic[cntCall++];
}


