//1652992786000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#define _Alignas(x)
struct tagFOO_ATTRIBUTE {
    unsigned int offset;
    unsigned int len;
    unsigned int id;
};

typedef struct tagFOO_ATTRIBUTE FOO_ATTRIBUTE;


