// 1652955986000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "memory_stub.h"

#define NULL ((void*)0)

int out_of_bound_access_to_heap_symbolic[10];
int out_of_bound_access_to_heap_symbolic[10];
int out_of_bound_access_to_heap(int num) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&out_of_bound_access_to_heap_symbolic, sizeof(out_of_bound_access_to_heap_symbolic), "out_of_bound_access_to_heap_symbolic");
            for (int it_36_0 = 0; it_36_0 < 10; it_36_0 ++) {
                klee_prefer_cex(out_of_bound_access_to_heap_symbolic, out_of_bound_access_to_heap_symbolic[it_36_0] >= -10  & out_of_bound_access_to_heap_symbolic[it_36_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return out_of_bound_access_to_heap_symbolic[cntCall++];
}


int out_of_bound_access_to_stack_symbolic[10];
int out_of_bound_access_to_stack_symbolic[10];
int out_of_bound_access_to_stack(int num) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&out_of_bound_access_to_stack_symbolic, sizeof(out_of_bound_access_to_stack_symbolic), "out_of_bound_access_to_stack_symbolic");
            for (int it_37_0 = 0; it_37_0 < 10; it_37_0 ++) {
                klee_prefer_cex(out_of_bound_access_to_stack_symbolic, out_of_bound_access_to_stack_symbolic[it_37_0] >= -10  & out_of_bound_access_to_stack_symbolic[it_37_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return out_of_bound_access_to_stack_symbolic[cntCall++];
}


int out_of_bound_access_to_globals_symbolic[10];
int out_of_bound_access_to_globals_symbolic[10];
int out_of_bound_access_to_globals(int i) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&out_of_bound_access_to_globals_symbolic, sizeof(out_of_bound_access_to_globals_symbolic), "out_of_bound_access_to_globals_symbolic");
            for (int it_39_0 = 0; it_39_0 < 10; it_39_0 ++) {
                klee_prefer_cex(out_of_bound_access_to_globals_symbolic, out_of_bound_access_to_globals_symbolic[it_39_0] >= -10  & out_of_bound_access_to_globals_symbolic[it_39_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return out_of_bound_access_to_globals_symbolic[cntCall++];
}


int use_after_free_symbolic[10];
int use_after_free_symbolic[10];
int use_after_free() {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&use_after_free_symbolic, sizeof(use_after_free_symbolic), "use_after_free_symbolic");
            for (int it_23_0 = 0; it_23_0 < 10; it_23_0 ++) {
                klee_prefer_cex(use_after_free_symbolic, use_after_free_symbolic[it_23_0] >= -10  & use_after_free_symbolic[it_23_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return use_after_free_symbolic[cntCall++];
}


char use_after_return_symbolic[10];
char use_after_return_symbolic[10];
char use_after_return() {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&use_after_return_symbolic, sizeof(use_after_return_symbolic), "use_after_return_symbolic");
            for (int it_25_0 = 0; it_25_0 < 10; it_25_0 ++) {
                klee_prefer_cex(use_after_return_symbolic, use_after_return_symbolic[it_25_0] >= 'a' & use_after_return_symbolic[it_25_0] <= 'z' & use_after_return_symbolic[it_25_0] != '\0');
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return use_after_return_symbolic[cntCall++];
}


int use_after_scope_symbolic[10];
int use_after_scope_symbolic[10];
int use_after_scope() {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&use_after_scope_symbolic, sizeof(use_after_scope_symbolic), "use_after_scope_symbolic");
            for (int it_24_0 = 0; it_24_0 < 10; it_24_0 ++) {
                klee_prefer_cex(use_after_scope_symbolic, use_after_scope_symbolic[it_24_0] >= -10  & use_after_scope_symbolic[it_24_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return use_after_scope_symbolic[cntCall++];
}


void double_free() {
    return;
}


int invalid_free_symbolic[10];
int invalid_free_symbolic[10];
int invalid_free() {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&invalid_free_symbolic, sizeof(invalid_free_symbolic), "invalid_free_symbolic");
            for (int it_21_0 = 0; it_21_0 < 10; it_21_0 ++) {
                klee_prefer_cex(invalid_free_symbolic, invalid_free_symbolic[it_21_0] >= -10  & invalid_free_symbolic[it_21_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return invalid_free_symbolic[cntCall++];
}


