//1656451884000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#define _Alignas(x)
typedef unsigned long size_t;

struct __locale_struct {
    struct __locale_data *__locales[13];
    const unsigned short *__ctype_b;
    const int *__ctype_tolower;
    const int *__ctype_toupper;
    const char *__names[13];
};

typedef struct __locale_struct *__locale_t;

typedef __locale_t locale_t;

struct MyStructMult {
    int a[2][3][2];
};

struct IntArray {
    int ints[2][5];
};

struct PointStruct {
    int x;
    int y;
};


