// 1656430451000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "static_stub.h"

#define NULL ((void*)0)

int inline_sum_symbolic[10];
int _inline_sum_symbolic[10];
int inline_sum(int a, int b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_inline_sum_symbolic, sizeof(_inline_sum_symbolic), "_inline_sum_symbolic");
            for (int it_117_0 = 0; it_117_0 < 10; it_117_0 ++) {
                klee_prefer_cex(_inline_sum_symbolic, _inline_sum_symbolic[it_117_0] >= -10  & _inline_sum_symbolic[it_117_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _inline_sum_symbolic[cntCall++];
}


