// 1656451698000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "symbolic_stdin_stub.h"

#define NULL ((void*)0)

int check_password_symbolic[10];
int _check_password_symbolic[10];
int check_password(int fd) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_check_password_symbolic, sizeof(_check_password_symbolic), "_check_password_symbolic");
            for (int it_118_0 = 0; it_118_0 < 10; it_118_0 ++) {
                klee_prefer_cex(_check_password_symbolic, _check_password_symbolic[it_118_0] >= -10  & _check_password_symbolic[it_118_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _check_password_symbolic[cntCall++];
}


