/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#include "floating_point_plain_test.h"

#include "gtest/gtest.h"
#include "math.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression

TEST(regression, plain_isnan_test_1)
{
    int actual = plain_isnan(0.000000e+00);
    EXPECT_EQ(0, actual);
}

TEST(regression, plain_isnan_test_2)
{
    int actual = plain_isnan(NAN);
    EXPECT_EQ(1, actual);
}

#pragma endregion
}
