//1652992786000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#define _Alignas(x)
typedef long ptrdiff_t;

typedef unsigned long size_t;

typedef struct {
    long long __max_align_ll __attribute__((aligned(__alignof(long long))));
    long double __max_align_ld __attribute__((aligned(__alignof(long double))));
} max_align_t;

struct Tree {
    struct Tree *left;
    struct Tree *right;
};


