// 1656430451000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "pointer_parameters_stub.h"

#define NULL ((void*)0)

int c_strcmp_symbolic[10];
int _c_strcmp_symbolic[10];
int c_strcmp(const char * a, const char * b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_c_strcmp_symbolic, sizeof(_c_strcmp_symbolic), "_c_strcmp_symbolic");
            for (int it_99_0 = 0; it_99_0 < 10; it_99_0 ++) {
                klee_prefer_cex(_c_strcmp_symbolic, _c_strcmp_symbolic[it_99_0] >= -10  & _c_strcmp_symbolic[it_99_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _c_strcmp_symbolic[cntCall++];
}


int ishello_symbolic[10];
int _ishello_symbolic[10];
int ishello(const char * a) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_ishello_symbolic, sizeof(_ishello_symbolic), "_ishello_symbolic");
            for (int it_100_0 = 0; it_100_0 < 10; it_100_0 ++) {
                klee_prefer_cex(_ishello_symbolic, _ishello_symbolic[it_100_0] >= -10  & _ishello_symbolic[it_100_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _ishello_symbolic[cntCall++];
}


int isworld_symbolic[10];
int _isworld_symbolic[10];
int isworld(const unsigned char * a) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_isworld_symbolic, sizeof(_isworld_symbolic), "_isworld_symbolic");
            for (int it_101_0 = 0; it_101_0 < 10; it_101_0 ++) {
                klee_prefer_cex(_isworld_symbolic, _isworld_symbolic[it_101_0] >= -10  & _isworld_symbolic[it_101_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _isworld_symbolic[cntCall++];
}


int longptr_cmp_symbolic[10];
int _longptr_cmp_symbolic[10];
int longptr_cmp(long * a, long * b) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_longptr_cmp_symbolic, sizeof(_longptr_cmp_symbolic), "_longptr_cmp_symbolic");
            for (int it_102_0 = 0; it_102_0 < 10; it_102_0 ++) {
                klee_prefer_cex(_longptr_cmp_symbolic, _longptr_cmp_symbolic[it_102_0] >= -10  & _longptr_cmp_symbolic[it_102_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _longptr_cmp_symbolic[cntCall++];
}


int void_pointer_int_usage_symbolic[10];
int _void_pointer_int_usage_symbolic[10];
int void_pointer_int_usage(void * x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_void_pointer_int_usage_symbolic, sizeof(_void_pointer_int_usage_symbolic), "_void_pointer_int_usage_symbolic");
            for (int it_103_0 = 0; it_103_0 < 10; it_103_0 ++) {
                klee_prefer_cex(_void_pointer_int_usage_symbolic, _void_pointer_int_usage_symbolic[it_103_0] >= -10  & _void_pointer_int_usage_symbolic[it_103_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _void_pointer_int_usage_symbolic[cntCall++];
}


int void_pointer_char_usage_symbolic[10];
int _void_pointer_char_usage_symbolic[10];
int void_pointer_char_usage(void * x) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_void_pointer_char_usage_symbolic, sizeof(_void_pointer_char_usage_symbolic), "_void_pointer_char_usage_symbolic");
            for (int it_104_0 = 0; it_104_0 < 10; it_104_0 ++) {
                klee_prefer_cex(_void_pointer_char_usage_symbolic, _void_pointer_char_usage_symbolic[it_104_0] >= -10  & _void_pointer_char_usage_symbolic[it_104_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _void_pointer_char_usage_symbolic[cntCall++];
}


