// 1656451698000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "complex_structs_stub.h"

#define NULL ((void*)0)

int struct_has_alphabet_symbolic[10];
int _struct_has_alphabet_symbolic[10];
int struct_has_alphabet(struct One st) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_struct_has_alphabet_symbolic, sizeof(_struct_has_alphabet_symbolic), "_struct_has_alphabet_symbolic");
            for (int it_25_0 = 0; it_25_0 < 10; it_25_0 ++) {
                klee_prefer_cex(_struct_has_alphabet_symbolic, _struct_has_alphabet_symbolic[it_25_0] >= -10  & _struct_has_alphabet_symbolic[it_25_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _struct_has_alphabet_symbolic[cntCall++];
}


char arrays_in_inner_structs_symbolic[10];
char _arrays_in_inner_structs_symbolic[10];
char arrays_in_inner_structs(struct Three st) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_arrays_in_inner_structs_symbolic, sizeof(_arrays_in_inner_structs_symbolic), "_arrays_in_inner_structs_symbolic");
            for (int it_26_0 = 0; it_26_0 < 10; it_26_0 ++) {
                klee_prefer_cex(_arrays_in_inner_structs_symbolic, _arrays_in_inner_structs_symbolic[it_26_0] >= 'a' & _arrays_in_inner_structs_symbolic[it_26_0] <= 'z' & _arrays_in_inner_structs_symbolic[it_26_0] != '\0');
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _arrays_in_inner_structs_symbolic[cntCall++];
}


struct One alphabet_symbolic[10];
struct One _alphabet_symbolic[10];
struct One alphabet(int a) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_alphabet_symbolic, sizeof(_alphabet_symbolic), "_alphabet_symbolic");
            for (int it_27_0 = 0; it_27_0 < 10; it_27_0 ++) {
                // No constraints for _alphabet_symbolic[it_27_0]
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _alphabet_symbolic[cntCall++];
}


