//1652992786000000000
//Please, do not change the line above
/*
 * This file is automatically generated by UnitTestBot. For further information see https://github.com/UnitTestBot/UTBotCpp
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#define _Alignas(x)
struct One {
    int a;
    char str[12];
};

struct Two {
    int ints[5];
};

struct Three {
    char chs[2];
    int b;
    struct Two in;
};


