name: "Check"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
  
env:
  utbot_version: "1.0.1"
    
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.inputs.logLevel }}
